
###### _____________ARCHARY PROJECT________________######
# Author List:		[ vidya vepoori]
# Filename:		MainUI.py

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setMinimumSize(QtCore.QSize(800, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.stackedWidget.setMinimumSize(QtCore.QSize(800, 800))
        self.stackedWidget.setMaximumSize(QtCore.QSize(2000, 2000))
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.stackedWidget.setMouseTracking(True)
        self.stackedWidget.setStyleSheet("QWidget#ArcheryPg{\n"
"background-color: qlineargradient(spread:pad, x1:0.079602, y1:0.0909091, x2:0.900498, y2:0.897727, stop:0 rgba(0, 226, 255, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.TitlePg = QtWidgets.QWidget()
        self.TitlePg.setStyleSheet("QWidget#TitlePg{\n"
"background-color: qlineargradient(spread:pad, x1:0.079602, y1:0.0909091, x2:0.900498, y2:0.897727, stop:0 rgba(0, 226, 255, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.TitlePg.setObjectName("TitlePg")
        self.groupBox = QtWidgets.QGroupBox(self.TitlePg)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 1920, 1081))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_1 = QtWidgets.QLabel(self.groupBox)
        self.label_1.setGeometry(QtCore.QRect(660, 290, 611, 131))
        self.label_1.setStyleSheet("font: 500  100pt \"Ubuntu\";\n"
"")
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(780, 500, 351, 41))
        self.label_2.setStyleSheet("font: 100 25pt \"Ubuntu\";")
        self.label_2.setObjectName("label_2")
        self.LoginBtn_1 = QtWidgets.QPushButton(self.groupBox)
        self.LoginBtn_1.setGeometry(QtCore.QRect(840, 610, 241, 81))
        self.LoginBtn_1.setStyleSheet("font: 200 45pt \"Ubuntu\";")
        self.LoginBtn_1.setObjectName("LoginBtn_1")
        self.quit_1 = QtWidgets.QPushButton(self.groupBox)
        self.quit_1.setGeometry(QtCore.QRect(1780, 30, 111, 21))
        self.quit_1.setObjectName("quit_1")
        self.stackedWidget.addWidget(self.TitlePg)
        self.LoginPg = QtWidgets.QWidget()
        self.LoginPg.setStyleSheet("QWidget#LoginPg{\n"
"background-color: qlineargradient(spread:pad, x1:0.079602, y1:0.0909091, x2:0.900498, y2:0.897727, stop:0 rgba(0, 226, 255, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.LoginPg.setObjectName("LoginPg")
        self.groupBox_2 = QtWidgets.QGroupBox(self.LoginPg)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 1921, 1080))
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(770, 280, 341, 51))
        self.label_7.setStyleSheet("font: 500 25pt \"Ubuntu\";")
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(880, 170, 141, 61))
        self.label_6.setStyleSheet("font: 500 36pt \"Ubuntu\";")
        self.label_6.setObjectName("label_6")
        self.back_2 = QtWidgets.QToolButton(self.groupBox_2)
        self.back_2.setGeometry(QtCore.QRect(1780, 30, 111, 21))
        self.back_2.setObjectName("back_2")
        self.quit_2 = QtWidgets.QToolButton(self.groupBox_2)
        self.quit_2.setGeometry(QtCore.QRect(1780, 70, 111, 21))
        self.quit_2.setObjectName("quit_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(770, 360, 131, 51))
        self.label_8.setStyleSheet("font: 500 20pt \"Ubuntu\";")
        self.label_8.setObjectName("label_8")
        self.loginBox = QtWidgets.QLineEdit(self.groupBox_2)
        self.loginBox.setGeometry(QtCore.QRect(770, 430, 341, 41))
        self.loginBox.setObjectName("loginBox")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(770, 490, 131, 51))
        self.label_9.setStyleSheet("font: 500 20pt \"Ubuntu\";")
        self.label_9.setObjectName("label_9")
        self.passwordBox = QtWidgets.QLineEdit(self.groupBox_2)
        self.passwordBox.setGeometry(QtCore.QRect(770, 550, 341, 41))
        self.passwordBox.setObjectName("passwordBox")
        self.l_error_1 = QtWidgets.QLabel(self.groupBox_2)
        self.l_error_1.setGeometry(QtCore.QRect(770, 630, 341, 31))
        self.l_error_1.setStyleSheet("color: rgb(239, 41, 41);")
        self.l_error_1.setText("")
        self.l_error_1.setObjectName("l_error_1")
        self.LoginBtn2 = QtWidgets.QPushButton(self.groupBox_2)
        self.LoginBtn2.setGeometry(QtCore.QRect(870, 700, 141, 41))
        self.LoginBtn2.setStyleSheet("font: 200 20pt \"Ubuntu\";")
        self.LoginBtn2.setObjectName("LoginBtn2")
        self.stackedWidget.addWidget(self.LoginPg)
        self.LevelPg = QtWidgets.QWidget()
        self.LevelPg.setStyleSheet("QWidget#LevelPg{\n"
"background-color: qlineargradient(spread:pad, x1:0.079602, y1:0.0909091, x2:0.900498, y2:0.897727, stop:0 rgba(0, 226, 255, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.LevelPg.setObjectName("LevelPg")
        self.groupBox_3 = QtWidgets.QGroupBox(self.LevelPg)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(880, 160, 161, 51))
        self.label_10.setStyleSheet("font: 500 36pt \"Ubuntu\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(810, 270, 341, 51))
        self.label_11.setStyleSheet("font: 500 25pt \"Ubuntu\";")
        self.label_11.setObjectName("label_11")
        self.quit_3 = QtWidgets.QToolButton(self.groupBox_3)
        self.quit_3.setGeometry(QtCore.QRect(1780, 30, 111, 21))
        self.quit_3.setObjectName("quit_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(760, 340, 381, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.b_national = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.b_national.setStyleSheet("font: 400 20pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:20px;\n"
"background-color: rgb(238, 238, 236);\n"
"")
        self.b_national.setObjectName("b_national")
        self.verticalLayout.addWidget(self.b_national)
        self.b_state = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.b_state.setStyleSheet("font: 400 20pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:20px;\n"
"background-color: rgb(238, 238, 236);")
        self.b_state.setObjectName("b_state")
        self.verticalLayout.addWidget(self.b_state)
        self.b_district = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.b_district.setStyleSheet("font: 400 20pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:20px;\n"
"background-color: rgb(238, 238, 236);")
        self.b_district.setObjectName("b_district")
        self.verticalLayout.addWidget(self.b_district)
        self.b_training = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.b_training.setStyleSheet("font: 400 20pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:20px;\n"
"background-color: rgb(238, 238, 236);")
        self.b_training.setObjectName("b_training")
        self.verticalLayout.addWidget(self.b_training)
        self.stackedWidget.addWidget(self.LevelPg)
        self.MatchPg = QtWidgets.QWidget()
        self.MatchPg.setStyleSheet("QWidget#MatchPg{\n"
"background-color: qlineargradient(spread:pad, x1:0.079602, y1:0.0909091, x2:0.900498, y2:0.897727, stop:0 rgba(0, 226, 255, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.MatchPg.setObjectName("MatchPg")
        self.groupBox_4 = QtWidgets.QGroupBox(self.MatchPg)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.groupBox_4.setStyleSheet("")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(770, 160, 521, 51))
        self.label_12.setStyleSheet("font: 500 36pt \"Ubuntu\";")
        self.label_12.setObjectName("label_12")
        self.rb_dual = QtWidgets.QRadioButton(self.groupBox_4)
        self.rb_dual.setGeometry(QtCore.QRect(600, 280, 291, 71))
        self.rb_dual.setStyleSheet("font: 300 24pt \"Ubuntu\";")
        self.rb_dual.setObjectName("rb_dual")
        self.l_distance = QtWidgets.QLabel(self.groupBox_4)
        self.l_distance.setGeometry(QtCore.QRect(1160, 250, 131, 51))
        self.l_distance.setStyleSheet("font: 500 20pt \"Ubuntu\";")
        self.l_distance.setObjectName("l_distance")
        self.distanceBox = QtWidgets.QLineEdit(self.groupBox_4)
        self.distanceBox.setGeometry(QtCore.QRect(1160, 300, 251, 41))
        self.distanceBox.setText("")
        self.distanceBox.setObjectName("distanceBox")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(1160, 350, 231, 21))
        self.label_14.setStyleSheet("color: rgb(239, 41, 41);")
        self.label_14.setObjectName("label_14")
        self.l_short = QtWidgets.QLabel(self.groupBox_4)
        self.l_short.setGeometry(QtCore.QRect(1160, 430, 181, 51))
        self.l_short.setStyleSheet("font: 500 20pt \"Ubuntu\";")
        self.l_short.setObjectName("l_short")
        self.shortBox = QtWidgets.QLineEdit(self.groupBox_4)
        self.shortBox.setGeometry(QtCore.QRect(1160, 480, 251, 41))
        self.shortBox.setObjectName("shortBox")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(1160, 530, 231, 21))
        self.label_15.setStyleSheet("color: rgb(239, 41, 41);")
        self.label_15.setObjectName("label_15")
        self.rb_single = QtWidgets.QRadioButton(self.groupBox_4)
        self.rb_single.setGeometry(QtCore.QRect(600, 470, 291, 71))
        self.rb_single.setStyleSheet("font: 300 24pt \"Ubuntu\";")
        self.rb_single.setObjectName("rb_single")
        self.quit_4 = QtWidgets.QToolButton(self.groupBox_4)
        self.quit_4.setGeometry(QtCore.QRect(1780, 70, 111, 21))
        self.quit_4.setObjectName("quit_4")
        self.back_4 = QtWidgets.QToolButton(self.groupBox_4)
        self.back_4.setGeometry(QtCore.QRect(1780, 30, 111, 21))
        self.back_4.setObjectName("back_4")
        self.l_error_2 = QtWidgets.QLabel(self.groupBox_4)
        self.l_error_2.setGeometry(QtCore.QRect(840, 610, 341, 31))
        self.l_error_2.setStyleSheet("color: rgb(239, 41, 41);")
        self.l_error_2.setText("")
        self.l_error_2.setObjectName("l_error_2")
        self.b_next_1 = QtWidgets.QPushButton(self.groupBox_4)
        self.b_next_1.setGeometry(QtCore.QRect(930, 670, 141, 41))
        self.b_next_1.setStyleSheet("font: 200 20pt \"Ubuntu\";")
        self.b_next_1.setObjectName("b_next_1")
        self.stackedWidget.addWidget(self.MatchPg)
        self.DualPg = QtWidgets.QWidget()
        self.DualPg.setStyleSheet("QWidget#DualPg{\n"
"background-color: qlineargradient(spread:pad, x1:0.079602, y1:0.0909091, x2:0.900498, y2:0.897727, stop:0 rgba(0, 226, 255, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.DualPg.setObjectName("DualPg")
        self.groupBox_5 = QtWidgets.QGroupBox(self.DualPg)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setGeometry(QtCore.QRect(860, 130, 341, 51))
        self.label_13.setAccessibleName("")
        self.label_13.setStyleSheet("font: 500 36pt \"Ubuntu\";")
        self.label_13.setObjectName("label_13")
        self.d_player_1 = QtWidgets.QLabel(self.groupBox_5)
        self.d_player_1.setGeometry(QtCore.QRect(600, 250, 201, 51))
        self.d_player_1.setStyleSheet("font: 500 20pt \"Ubuntu\";")
        self.d_player_1.setObjectName("d_player_1")
        self.player1Box_1 = QtWidgets.QLineEdit(self.groupBox_5)
        self.player1Box_1.setGeometry(QtCore.QRect(910, 260, 311, 41))
        self.player1Box_1.setObjectName("player1Box_1")
        self.d_player_2 = QtWidgets.QLabel(self.groupBox_5)
        self.d_player_2.setGeometry(QtCore.QRect(600, 360, 251, 51))
        self.d_player_2.setStyleSheet("font: 500 20pt \"Ubuntu\";")
        self.d_player_2.setObjectName("d_player_2")
        self.player2Box_1 = QtWidgets.QLineEdit(self.groupBox_5)
        self.player2Box_1.setGeometry(QtCore.QRect(910, 370, 311, 41))
        self.player2Box_1.setObjectName("player2Box_1")
        self.d_country = QtWidgets.QLabel(self.groupBox_5)
        self.d_country.setGeometry(QtCore.QRect(600, 470, 181, 51))
        self.d_country.setStyleSheet("font: 500 20pt \"Ubuntu\";")
        self.d_country.setObjectName("d_country")
        self.countryBox_1 = QtWidgets.QLineEdit(self.groupBox_5)
        self.countryBox_1.setGeometry(QtCore.QRect(910, 480, 311, 41))
        self.countryBox_1.setObjectName("countryBox_1")
        self.l_error = QtWidgets.QLabel(self.groupBox_5)
        self.l_error.setGeometry(QtCore.QRect(780, 630, 271, 20))
        self.l_error.setStyleSheet("color: rgb(239, 41, 41);")
        self.l_error.setText("")
        self.l_error.setObjectName("l_error")
        self.back_5 = QtWidgets.QToolButton(self.groupBox_5)
        self.back_5.setGeometry(QtCore.QRect(1780, 30, 111, 21))
        self.back_5.setObjectName("back_5")
        self.quit_5 = QtWidgets.QToolButton(self.groupBox_5)
        self.quit_5.setGeometry(QtCore.QRect(1780, 70, 111, 21))
        self.quit_5.setObjectName("quit_5")
        self.StartBtn_1 = QtWidgets.QPushButton(self.groupBox_5)
        self.StartBtn_1.setGeometry(QtCore.QRect(850, 690, 121, 41))
        self.StartBtn_1.setStyleSheet("font: 200\n"
" 20pt \"Ubuntu\";")
        self.StartBtn_1.setObjectName("StartBtn_1")
        self.stackedWidget.addWidget(self.DualPg)
        self.SinglePg = QtWidgets.QWidget()
        self.SinglePg.setStyleSheet("QWidget#SinglePg{\n"
"background-color: qlineargradient(spread:pad, x1:0.079602, y1:0.0909091, x2:0.900498, y2:0.897727, stop:0 rgba(0, 226, 255, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.SinglePg.setObjectName("SinglePg")
        self.groupBox_6 = QtWidgets.QGroupBox(self.SinglePg)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setGeometry(QtCore.QRect(860, 130, 161, 51))
        self.label_4.setStyleSheet("font: 500 36pt \"Ubuntu\";")
        self.label_4.setObjectName("label_4")
        self.l_distance_4 = QtWidgets.QLabel(self.groupBox_6)
        self.l_distance_4.setGeometry(QtCore.QRect(620, 310, 201, 51))
        self.l_distance_4.setStyleSheet("font: 500 20pt \"Ubuntu\";")
        self.l_distance_4.setObjectName("l_distance_4")
        self.player1Box_2 = QtWidgets.QLineEdit(self.groupBox_6)
        self.player1Box_2.setGeometry(QtCore.QRect(910, 310, 311, 41))
        self.player1Box_2.setObjectName("player1Box_2")
        self.l_short_3 = QtWidgets.QLabel(self.groupBox_6)
        self.l_short_3.setGeometry(QtCore.QRect(620, 430, 181, 51))
        self.l_short_3.setStyleSheet("font: 500 20pt \"Ubuntu\";")
        self.l_short_3.setObjectName("l_short_3")
        self.countryBox_2 = QtWidgets.QLineEdit(self.groupBox_6)
        self.countryBox_2.setGeometry(QtCore.QRect(910, 440, 311, 41))
        self.countryBox_2.setObjectName("countryBox_2")
        self.l_error_4 = QtWidgets.QLabel(self.groupBox_6)
        self.l_error_4.setGeometry(QtCore.QRect(800, 600, 271, 20))
        self.l_error_4.setStyleSheet("color: rgb(239, 41, 41);")
        self.l_error_4.setText("")
        self.l_error_4.setObjectName("l_error_4")
        self.back_6 = QtWidgets.QToolButton(self.groupBox_6)
        self.back_6.setGeometry(QtCore.QRect(1780, 30, 111, 21))
        self.back_6.setObjectName("back_6")
        self.quit_6 = QtWidgets.QToolButton(self.groupBox_6)
        self.quit_6.setGeometry(QtCore.QRect(1780, 70, 111, 21))
        self.quit_6.setObjectName("quit_6")
        self.StartBtn_2 = QtWidgets.QPushButton(self.groupBox_6)
        self.StartBtn_2.setGeometry(QtCore.QRect(880, 650, 121, 41))
        self.StartBtn_2.setStyleSheet("font: 200\n"
" 20pt \"Ubuntu\";")
        self.StartBtn_2.setObjectName("StartBtn_2")
        self.stackedWidget.addWidget(self.SinglePg)
        self.TrainingPg = QtWidgets.QWidget()
        self.TrainingPg.setStyleSheet("QWidget#TrainingPg{\n"
"background-color: qlineargradient(spread:pad, x1:0.079602, y1:0.0909091, x2:0.900498, y2:0.897727, stop:0 rgba(0, 226, 255, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.TrainingPg.setObjectName("TrainingPg")
        self.groupBox_8 = QtWidgets.QGroupBox(self.TrainingPg)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.groupBox_8.setStyleSheet("")
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.back_7 = QtWidgets.QToolButton(self.groupBox_8)
        self.back_7.setGeometry(QtCore.QRect(1780, 30, 111, 21))
        self.back_7.setObjectName("back_7")
        self.quit_7 = QtWidgets.QToolButton(self.groupBox_8)
        self.quit_7.setGeometry(QtCore.QRect(1780, 70, 111, 21))
        self.quit_7.setObjectName("quit_7")
        self.label_5 = QtWidgets.QLabel(self.groupBox_8)
        self.label_5.setGeometry(QtCore.QRect(870, 120, 221, 51))
        self.label_5.setStyleSheet("font: 500 36pt \"Ubuntu\";")
        self.label_5.setObjectName("label_5")
        self.l_distance_5 = QtWidgets.QLabel(self.groupBox_8)
        self.l_distance_5.setGeometry(QtCore.QRect(720, 300, 131, 51))
        self.l_distance_5.setStyleSheet("font: 500 20pt \"Ubuntu\";")
        self.l_distance_5.setObjectName("l_distance_5")
        self.distance_field_2 = QtWidgets.QLineEdit(self.groupBox_8)
        self.distance_field_2.setGeometry(QtCore.QRect(940, 300, 251, 41))
        self.distance_field_2.setObjectName("distance_field_2")
        self.l_short_4 = QtWidgets.QLabel(self.groupBox_8)
        self.l_short_4.setGeometry(QtCore.QRect(720, 420, 181, 51))
        self.l_short_4.setStyleSheet("font: 500 20pt \"Ubuntu\";")
        self.l_short_4.setObjectName("l_short_4")
        self.short_field_2 = QtWidgets.QLineEdit(self.groupBox_8)
        self.short_field_2.setGeometry(QtCore.QRect(940, 420, 251, 41))
        self.short_field_2.setObjectName("short_field_2")
        self.b_next_2 = QtWidgets.QPushButton(self.groupBox_8)
        self.b_next_2.setGeometry(QtCore.QRect(880, 620, 141, 41))
        self.b_next_2.setStyleSheet("font: 200\n"
" 20pt \"Ubuntu\";")
        self.b_next_2.setObjectName("b_next_2")
        self.l_error_5 = QtWidgets.QLabel(self.groupBox_8)
        self.l_error_5.setGeometry(QtCore.QRect(830, 570, 271, 20))
        self.l_error_5.setStyleSheet("color: rgb(239, 41, 41);")
        self.l_error_5.setText("")
        self.l_error_5.setObjectName("l_error_5")
        self.stackedWidget.addWidget(self.TrainingPg)
        self.StartPg = QtWidgets.QWidget()
        self.StartPg.setStyleSheet("QWidget#StartPg{\n"
"background-color: qlineargradient(spread:pad, x1:0.079602, y1:0.0909091, x2:0.900498, y2:0.897727, stop:0 rgba(0, 226, 255, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.StartPg.setObjectName("StartPg")
        self.StartBtn2 = QtWidgets.QPushButton(self.StartPg)
        self.StartBtn2.setGeometry(QtCore.QRect(820, 550, 261, 71))
        self.StartBtn2.setStyleSheet("font: 500\n"
" 36pt \"Ubuntu\";")
        self.StartBtn2.setObjectName("StartBtn2")
        self.back_8 = QtWidgets.QToolButton(self.StartPg)
        self.back_8.setGeometry(QtCore.QRect(1780, 30, 111, 21))
        self.back_8.setObjectName("back_8")
        self.quit_8 = QtWidgets.QToolButton(self.StartPg)
        self.quit_8.setGeometry(QtCore.QRect(1780, 70, 111, 21))
        self.quit_8.setObjectName("quit_8")
        self.timeBox = QtWidgets.QLabel(self.StartPg)
        self.timeBox.setGeometry(QtCore.QRect(850, 270, 201, 181))
        self.timeBox.setText("")
        self.timeBox.setObjectName("timeBox")
        self.Score_btn = QtWidgets.QPushButton(self.StartPg)
        self.Score_btn.setGeometry(QtCore.QRect(820, 700, 261, 71))
        self.Score_btn.setStyleSheet("font: 500\n"
" 36pt \"Ubuntu\";")
        self.Score_btn.setObjectName("Score_btn")
        self.stackedWidget.addWidget(self.StartPg)
        self.ScorePg = QtWidgets.QWidget()
        self.ScorePg.setStyleSheet("QWidget#ScorePg{\n"
"background-color: qlineargradient(spread:pad, x1:0.079602, y1:0.0909091, x2:0.900498, y2:0.897727, stop:0 rgba(0, 226, 255, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.ScorePg.setObjectName("ScorePg")
        self.back_9 = QtWidgets.QToolButton(self.ScorePg)
        self.back_9.setGeometry(QtCore.QRect(1780, 30, 111, 21))
        self.back_9.setObjectName("back_9")
        self.quit_9 = QtWidgets.QToolButton(self.ScorePg)
        self.quit_9.setGeometry(QtCore.QRect(1780, 70, 111, 21))
        self.quit_9.setObjectName("quit_9")
        self.label = QtWidgets.QLabel(self.ScorePg)
        self.label.setGeometry(QtCore.QRect(370, 100, 261, 51))
        self.label.setStyleSheet("font: 500 36pt \"Ubuntu\";")
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.ScorePg)
        self.ArcheryPg = QtWidgets.QWidget()
        self.ArcheryPg.setObjectName("ArcheryPg")
        self.widget = QtWidgets.QWidget(self.ArcheryPg)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1000, 1000))
        self.widget.setStyleSheet("background-color: rgb(233, 185, 110);")
        self.widget.setObjectName("widget")
        self.stackedWidget.addWidget(self.ArcheryPg)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_1.setText(_translate("MainWindow", "ARCHERY"))
        self.label_2.setText(_translate("MainWindow", "Login in to your account"))
        self.LoginBtn_1.setText(_translate("MainWindow", "Login"))
        self.quit_1.setText(_translate("MainWindow", "Quit"))
        self.label_7.setText(_translate("MainWindow", "Signin to your Existing Account"))
        self.label_6.setText(_translate("MainWindow", "Login"))
        self.back_2.setText(_translate("MainWindow", "Back"))
        self.quit_2.setText(_translate("MainWindow", "Quit"))
        self.label_8.setText(_translate("MainWindow", "Login ID :"))
        self.label_9.setText(_translate("MainWindow", "Password :"))
        self.LoginBtn2.setText(_translate("MainWindow", "Login"))
        self.label_10.setText(_translate("MainWindow", "Levels"))
        self.label_11.setText(_translate("MainWindow", "Choose your level :"))
        self.quit_3.setText(_translate("MainWindow", "Quit"))
        self.b_national.setText(_translate("MainWindow", "National Level"))
        self.b_state.setText(_translate("MainWindow", "State/Province Level"))
        self.b_district.setText(_translate("MainWindow", "District Level"))
        self.b_training.setText(_translate("MainWindow", "Training"))
        self.label_12.setText(_translate("MainWindow", "Choose your Match :"))
        self.rb_dual.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.rb_dual.setText(_translate("MainWindow", "Dual Match | 2 vs 2"))
        self.l_distance.setText(_translate("MainWindow", "Distance :"))
        self.label_14.setText(_translate("MainWindow", "* enter as integer ex: 20"))
        self.l_short.setText(_translate("MainWindow", "No.of Shorts :"))
        self.label_15.setText(_translate("MainWindow", "* enter as integer ex: 4"))
        self.rb_single.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.rb_single.setText(_translate("MainWindow", "Singles | 1 on 1"))
        self.quit_4.setText(_translate("MainWindow", "Quit"))
        self.back_4.setText(_translate("MainWindow", "Back"))
        self.b_next_1.setText(_translate("MainWindow", "Next"))
        self.label_13.setText(_translate("MainWindow", "Details"))
        self.d_player_1.setText(_translate("MainWindow", "Player_1 Name :"))
        self.d_player_2.setText(_translate("MainWindow", "Player_2 Name :"))
        self.d_country.setText(_translate("MainWindow", "Country :"))
        self.back_5.setText(_translate("MainWindow", "Back"))
        self.quit_5.setText(_translate("MainWindow", "Quit"))
        self.StartBtn_1.setText(_translate("MainWindow", "Start"))
        self.label_4.setText(_translate("MainWindow", "Details"))
        self.l_distance_4.setText(_translate("MainWindow", "Player_1 Name :"))
        self.l_short_3.setText(_translate("MainWindow", "Country :"))
        self.back_6.setText(_translate("MainWindow", "Back"))
        self.quit_6.setText(_translate("MainWindow", "Quit"))
        self.StartBtn_2.setText(_translate("MainWindow", "Start"))
        self.back_7.setText(_translate("MainWindow", "Back"))
        self.quit_7.setText(_translate("MainWindow", "Quit"))
        self.label_5.setText(_translate("MainWindow", "Training :"))
        self.l_distance_5.setText(_translate("MainWindow", "Distance :"))
        self.l_short_4.setText(_translate("MainWindow", "No.of Shorts :"))
        self.b_next_2.setText(_translate("MainWindow", "Next"))
        self.StartBtn2.setText(_translate("MainWindow", "Start"))
        self.back_8.setText(_translate("MainWindow", "Back"))
        self.quit_8.setText(_translate("MainWindow", "Quit"))
        self.Score_btn.setText(_translate("MainWindow", "Score Card"))
        self.back_9.setText(_translate("MainWindow", "Back"))
        self.quit_9.setText(_translate("MainWindow", "Quit"))
        self.label.setText(_translate("MainWindow", "Score Card:"))
